insert into adresa (id, grad, ulica, broj, drzava) values (1, 'Itiruçu', '3rd', '4', 'Brazil');
insert into adresa (id, grad, ulica, broj, drzava) values (2, 'Didian', 'Talmadge', '21', 'China');
insert into adresa (id, grad, ulica, broj, drzava) values (3, 'San Jacinto', 'Hoepker', '75554', 'Philippines');
insert into adresa (id, grad, ulica, broj, drzava) values (4, 'Muang Xay', 'Lillian', '80688', 'Laos');
insert into adresa (id, grad, ulica, broj, drzava) values (5, 'Pirogovo', 'Sheridan', '17', 'Russia');
insert into adresa (id, grad, ulica, broj, drzava) values (6, 'Klenje', 'Northwestern', '6636', 'Serbia');
insert into adresa (id, grad, ulica, broj, drzava) values (7, 'Zwettl', 'Anzinger', '78189', 'Austria');
insert into adresa (id, grad, ulica, broj, drzava) values (8, 'Sidaohezi', 'Village Green', '80', 'China');
insert into adresa (id, grad, ulica, broj, drzava) values (9, 'São Marcos', 'Hooker', '07', 'Brazil');
insert into adresa (id, grad, ulica, broj, drzava) values (10, 'Kyzyl-Kyya', 'Carpenter', '112', 'Kyrgyzstan');
insert into adresa (id, grad, ulica, broj, drzava) values (11, 'Inglewood', 'Independence', '932', 'United States');
insert into adresa (id, grad, ulica, broj, drzava) values (12, 'Jablanovec', 'Daystar', '54821', 'Croatia');
insert into adresa (id, grad, ulica, broj, drzava) values (13, 'Leiling', 'Maple Wood', '6746', 'China');
insert into adresa (id, grad, ulica, broj, drzava) values (14, 'Turar Ryskulov', 'Meadow Valley', '59', 'Kazakhstan');
insert into adresa (id, grad, ulica, broj, drzava) values (15, 'Argel', 'Del Mar', '62', 'Armenia');
insert into adresa (id, grad, ulica, broj, drzava) values (16, 'Cimongkor', 'Cascade', '408', 'Indonesia');
insert into adresa (id, grad, ulica, broj, drzava) values (17, 'Paucarbamba', 'Kensington', '797', 'Peru');
insert into adresa (id, grad, ulica, broj, drzava) values (18, 'Checun', 'Ludington', '5074', 'China');
insert into adresa (id, grad, ulica, broj, drzava) values (19, 'Hexi', 'Twin Pines', '666', 'China');
insert into adresa (id, grad, ulica, broj, drzava) values (20, 'Pontevedra', 'Rieder', '3268', 'Spain');
insert into adresa (id, grad, ulica, broj, drzava) values (21, 'Topi', 'Scoville', '42', 'Pakistan');
insert into adresa (id, grad, ulica, broj, drzava) values (22, 'Xichuan', 'Karstens', '66327', 'China');
insert into adresa (id, grad, ulica, broj, drzava) values (23, 'Fristad', 'Dorton', '13578', 'Sweden');
insert into adresa (id, grad, ulica, broj, drzava) values (24, 'Ţūlkarm', 'Declaration', '90825', 'Palestinian Territory');
insert into adresa (id, grad, ulica, broj, drzava) values (25, 'Congonhas', 'Fieldstone', '7', 'Brazil');
insert into adresa (id, grad, ulica, broj, drzava) values (26, 'Taiyang', 'Jackson', '400', 'China');
insert into adresa (id, grad, ulica, broj, drzava) values (27, 'Sali', 'Hudson', '9', 'Croatia');
insert into adresa (id, grad, ulica, broj, drzava) values (28, 'Íasmos', 'Pawling', '7311', 'Greece');
insert into adresa (id, grad, ulica, broj, drzava) values (29, 'Banquero', 'Paget', '69', 'Philippines');
insert into adresa (id, grad, ulica, broj, drzava) values (30, 'Zlynka', 'Esker', '91635', 'Ukraine');
insert into adresa (id, grad, ulica, broj, drzava) values (31, 'Itamarandiba', 'Westerfield', '4037', 'Brazil');
insert into adresa (id, grad, ulica, broj, drzava) values (32, 'Songshan', 'Pankratz', '8', 'China');
insert into adresa (id, grad, ulica, broj, drzava) values (33, 'Obninsk', 'Butternut', '0', 'Russia');
insert into adresa (id, grad, ulica, broj, drzava) values (34, 'Muara Sabak', 'Pepper Wood', '5', 'Indonesia');
insert into adresa (id, grad, ulica, broj, drzava) values (35, 'Kamigyō-ku', 'Haas', '8', 'Japan');
insert into adresa (id, grad, ulica, broj, drzava) values (36, 'Ngandangan', 'Milwaukee', '54542', 'Indonesia');
insert into adresa (id, grad, ulica, broj, drzava) values (37, 'Bum Bum', 'Esch', '3401', 'Venezuela');
insert into adresa (id, grad, ulica, broj, drzava) values (38, 'Senovo', 'Kipling', '87844', 'Slovenia');
insert into adresa (id, grad, ulica, broj, drzava) values (39, 'Budzów', 'Golden Leaf', '47905', 'Poland');
insert into adresa (id, grad, ulica, broj, drzava) values (40, 'Kamenskiy', 'East', '7', 'Russia');
insert into adresa (id, grad, ulica, broj, drzava) values (41, 'Villa Nueva', 'Warner', '84628', 'Argentina');
insert into adresa (id, grad, ulica, broj, drzava) values (42, 'Saint-Denis', 'Caliangt', '493', 'Reunion');
insert into adresa (id, grad, ulica, broj, drzava) values (43, 'Denver', 'Sutherland', '5', 'United States');
insert into adresa (id, grad, ulica, broj, drzava) values (44, 'Áyios Vasílios', 'Heffernan', '3755', 'Greece');
insert into adresa (id, grad, ulica, broj, drzava) values (45, 'Lebak', 'Tony', '9', 'Indonesia');
insert into adresa (id, grad, ulica, broj, drzava) values (46, 'Kanbe', 'Roxbury', '62633', 'Myanmar');
insert into adresa (id, grad, ulica, broj, drzava) values (47, 'Mendeleyevo', 'Almo', '70989', 'Russia');
insert into adresa (id, grad, ulica, broj, drzava) values (48, 'Shemonaīkha', 'Victoria', '524', 'Kazakhstan');
insert into adresa (id, grad, ulica, broj, drzava) values (49, 'Japeri', 'Annamark', '15', 'Brazil');
insert into adresa (id, grad, ulica, broj, drzava) values (50, 'Pointe-à-Pitre', 'Novick', '2221', 'Guadeloupe');
insert into adresa (id, grad, ulica, broj, drzava) values (51, 'Stupari', 'Charing Cross', '98465', 'Bosnia and Herzegovina');
insert into adresa (id, grad, ulica, broj, drzava) values (52, 'Bauan', 'Bobwhite', '037', 'Philippines');
insert into adresa (id, grad, ulica, broj, drzava) values (53, 'Alcácer do Sal', 'Randy', '62183', 'Portugal');
insert into adresa (id, grad, ulica, broj, drzava) values (54, 'El Banco', 'Bultman', '78', 'Colombia');
insert into adresa (id, grad, ulica, broj, drzava) values (55, 'Brétigny-sur-Orge', 'Mallard', '1', 'France');
insert into adresa (id, grad, ulica, broj, drzava) values (56, 'Molodizhne', 'Del Mar', '29', 'Ukraine');
insert into adresa (id, grad, ulica, broj, drzava) values (57, 'Kinlough', 'Ramsey', '2419', 'Ireland');
insert into adresa (id, grad, ulica, broj, drzava) values (58, 'Donggou', 'Scoville', '997', 'China');
insert into adresa (id, grad, ulica, broj, drzava) values (59, 'Congkar', 'Calypso', '7470', 'Indonesia');
insert into adresa (id, grad, ulica, broj, drzava) values (60, 'Krông Kmar', 'Hoepker', '09327', 'Vietnam');
insert into adresa (id, grad, ulica, broj, drzava) values (61, 'Apeldoorn', 'Gerald', '7', 'Netherlands');
insert into adresa (id, grad, ulica, broj, drzava) values (62, 'Khānpur', 'Del Sol', '79', 'Pakistan');
insert into adresa (id, grad, ulica, broj, drzava) values (63, 'Natitingou', 'Forest', '56578', 'Benin');
insert into adresa (id, grad, ulica, broj, drzava) values (64, 'Bambanglipuro', 'Lindbergh', '9877', 'Indonesia');
insert into adresa (id, grad, ulica, broj, drzava) values (65, 'Rouen', 'Green Ridge', '01', 'France');
insert into adresa (id, grad, ulica, broj, drzava) values (66, 'Xuedian', 'Express', '59808', 'China');
insert into adresa (id, grad, ulica, broj, drzava) values (67, 'Konstantinovskoye', 'Rutledge', '433', 'Russia');
insert into adresa (id, grad, ulica, broj, drzava) values (68, 'Konispol', 'Brentwood', '08', 'Albania');
insert into adresa (id, grad, ulica, broj, drzava) values (69, 'Yanac', 'Old Shore', '10011', 'Peru');
insert into adresa (id, grad, ulica, broj, drzava) values (70, 'Magole', 'Mallard', '3', 'Tanzania');
insert into adresa (id, grad, ulica, broj, drzava) values (71, 'Maco', 'Center', '8', 'Philippines');
insert into adresa (id, grad, ulica, broj, drzava) values (72, 'Anju', 'Summerview', '12644', 'China');
insert into adresa (id, grad, ulica, broj, drzava) values (73, 'Julayjilah', 'Scofield', '5834', 'Saudi Arabia');
insert into adresa (id, grad, ulica, broj, drzava) values (74, 'Nancun', 'Corry', '9545', 'China');
insert into adresa (id, grad, ulica, broj, drzava) values (75, 'Romblon', 'Eagan', '05365', 'Philippines');
insert into adresa (id, grad, ulica, broj, drzava) values (76, 'Hudiksvall', 'Mendota', '60', 'Sweden');
insert into adresa (id, grad, ulica, broj, drzava) values (77, 'Bendungan', 'Meadow Vale', '1660', 'Indonesia');
insert into adresa (id, grad, ulica, broj, drzava) values (78, 'Trelleborg', 'Lerdahl', '7278', 'Sweden');
insert into adresa (id, grad, ulica, broj, drzava) values (79, 'Wenping', 'Brentwood', '60576', 'China');
insert into adresa (id, grad, ulica, broj, drzava) values (80, 'Puconci', 'Northport', '90', 'Slovenia');
insert into adresa (id, grad, ulica, broj, drzava) values (81, 'Jongīyeh', 'Messerschmidt', '1', 'Iran');
insert into adresa (id, grad, ulica, broj, drzava) values (82, 'Vitoria-Gasteiz', 'Rowland', '7826', 'Spain');
insert into adresa (id, grad, ulica, broj, drzava) values (83, 'Mucllo', 'Clemons', '50222', 'Peru');
insert into adresa (id, grad, ulica, broj, drzava) values (84, 'Valerianovsk', 'Sloan', '3687', 'Russia');
insert into adresa (id, grad, ulica, broj, drzava) values (85, 'Agboville', 'Mockingbird', '37', 'Ivory Coast');
insert into adresa (id, grad, ulica, broj, drzava) values (86, 'Graz', 'Waywood', '95', 'Austria');
insert into adresa (id, grad, ulica, broj, drzava) values (87, 'Mahong', 'Daystar', '6225', 'China');
insert into adresa (id, grad, ulica, broj, drzava) values (88, 'Lumbac', 'Merrick', '3798', 'Philippines');
insert into adresa (id, grad, ulica, broj, drzava) values (89, 'Yaruchel', 'Gale', '41571', 'Honduras');
insert into adresa (id, grad, ulica, broj, drzava) values (90, 'Derbur', 'Vernon', '9', 'China');
insert into adresa (id, grad, ulica, broj, drzava) values (91, 'Quỳnh Côi', 'Ryan', '53', 'Vietnam');
insert into adresa (id, grad, ulica, broj, drzava) values (92, 'Iwai', 'Oxford', '00010', 'Japan');
insert into adresa (id, grad, ulica, broj, drzava) values (93, 'Santo Tomas', 'Armistice', '17', 'Peru');
insert into adresa (id, grad, ulica, broj, drzava) values (94, 'Wilczyce', 'Pennsylvania', '89', 'Poland');
insert into adresa (id, grad, ulica, broj, drzava) values (95, 'Belozërskoye', 'Burning Wood', '6132', 'Russia');
insert into adresa (id, grad, ulica, broj, drzava) values (96, 'Keffin Hausa', 'Sugar', '10', 'Nigeria');
insert into adresa (id, grad, ulica, broj, drzava) values (97, 'Gurung', 'Rowland', '22', 'Indonesia');
insert into adresa (id, grad, ulica, broj, drzava) values (98, 'Pinega', 'Paget', '4062', 'Russia');
insert into adresa (id, grad, ulica, broj, drzava) values (99, 'Thanatpin', 'Graceland', '059', 'Myanmar');
insert into adresa (id, grad, ulica, broj, drzava) values (100, 'Kelapa', 'Toban', '9493', 'Indonesia');