insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (1, 1, 'Hettinger-Cassin', 1);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (2, 2, 'Johnston, Erdman and Corwin', 2);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (3, 3, 'Borer, Koch and Herman', 3);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (4, 4, 'Koelpin-Schumm', 4);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (5, 5, 'Schuster and Sons', 5);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (6, 6, 'Labadie, Bauch and Jenkins', 6);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (7, 7, 'Aufderhar, Sauer and Jakubowski', 7);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (8, 8, 'Veum-Leuschke', 8);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (9, 9, 'O''Connell, Rempel and Collins', 9);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (10, 10, 'Waters, Lindgren and Hessel', 10);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (11, 11, 'Johns, Hyatt and Watsica', 11);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (12, 12, 'Effertz-Wunsch', 12);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (13, 13, 'Kertzmann-Lindgren', 13);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (14, 14, 'Schmidt, Nikolaus and O''Hara', 14);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (15, 15, 'Pagac LLC', 15);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (16, 16, 'Rogahn, Rutherford and Stehr', 16);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (17, 17, 'Lindgren, Hartmann and Kassulke', 17);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (18, 18, 'Bauch, Schultz and Howell', 18);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (19, 19, 'Shields, Lind and Schulist', 19);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (20, 20, 'Goldner and Sons', 20);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (21, 21, 'Zemlak-Padberg', 21);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (22, 22, 'Gislason Inc', 22);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (23, 23, 'Kemmer, Wiegand and Mueller', 23);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (24, 24, 'White-Marvin', 24);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (25, 25, 'Fisher-Zboncak', 25);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (26, 26, 'Dibbert, Doyle and Muller', 26);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (27, 27, 'Lowe-O''Hara', 27);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (28, 28, 'Cremin LLC', 28);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (29, 29, 'McKenzie-Schumm', 29);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (30, 30, 'Huels, Boyer and Kuhn', 30);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (31, 31, 'Hansen, Casper and Dare', 31);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (32, 32, 'Kub-Hagenes', 32);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (33, 33, 'Hauck, Rohan and DuBuque', 33);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (34, 34, 'Nitzsche-Lebsack', 34);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (35, 35, 'Rolfson, Bartell and Daniel', 35);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (36, 36, 'Emard, Cremin and Corkery', 36);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (37, 37, 'Upton, Harris and Gulgowski', 37);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (38, 38, 'Gusikowski, Larson and Corwin', 38);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (39, 39, 'Bartell, Bashirian and Stiedemann', 39);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (40, 40, 'Kozey, Kertzmann and Green', 40);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (41, 41, 'Gerhold, Bernier and Krajcik', 41);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (42, 42, 'Jacobs-Dach', 42);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (43, 43, 'Pfannerstill Inc', 43);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (44, 44, 'Quigley, Marquardt and Rippin', 44);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (45, 45, 'Corwin, Stroman and Jacobs', 45);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (46, 46, 'Murphy-Gaylord', 46);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (47, 47, 'Cormier-Doyle', 47);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (48, 48, 'Considine-Simonis', 48);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (49, 49, 'Deckow LLC', 49);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (50, 50, 'Haley-Moore', 50);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (51, 51, 'Goyette Group', 51);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (52, 52, 'Berge, Will and Stoltenberg', 52);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (53, 53, 'Friesen LLC', 53);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (54, 54, 'Cassin, Gerhold and Tromp', 54);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (55, 55, 'Larson, Harber and Block', 55);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (56, 56, 'Bayer-Trantow', 56);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (57, 57, 'Oberbrunner, Bednar and Bergstrom', 57);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (58, 58, 'Donnelly-McClure', 58);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (59, 59, 'Russel, Kemmer and Daugherty', 59);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (60, 60, 'Upton Inc', 60);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (61, 61, 'Langworth, Torp and Waters', 61);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (62, 62, 'Heller, Glover and Barrows', 62);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (63, 63, 'Bruen-Daugherty', 63);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (64, 64, 'Davis Group', 64);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (65, 65, 'Hane LLC', 65);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (66, 66, 'Hand, Haley and Cruickshank', 66);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (67, 67, 'Hessel Inc', 67);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (68, 68, 'Abernathy, Kshlerin and Gleichner', 68);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (69, 69, 'Stroman and Sons', 69);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (70, 70, 'Hand-Romaguera', 70);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (71, 71, 'Denesik and Sons', 71);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (72, 72, 'Jast-McLaughlin', 72);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (73, 73, 'Wilkinson and Sons', 73);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (74, 74, 'Roob Group', 74);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (75, 75, 'Wehner and Sons', 75);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (76, 76, 'Wunsch, Oberbrunner and Haley', 76);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (77, 77, 'Boyle Group', 77);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (78, 78, 'Bosco and Sons', 78);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (79, 79, 'Goyette, Legros and Keeling', 79);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (80, 80, 'Fay, Johns and Carroll', 80);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (81, 81, 'Terry, Wintheiser and Kub', 81);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (82, 82, 'Blanda Group', 82);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (83, 83, 'Koelpin Inc', 83);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (84, 84, 'Bode, Cremin and Mosciski', 84);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (85, 85, 'Ritchie Group', 85);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (86, 86, 'Bergnaum, Mueller and Boehm', 86);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (87, 87, 'Bogan and Sons', 87);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (88, 88, 'Wolff Inc', 88);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (89, 89, 'Effertz-Goyette', 89);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (90, 90, 'Schuppe Inc', 90);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (91, 91, 'Fadel-Goodwin', 91);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (92, 92, 'Lebsack-Hackett', 92);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (93, 93, 'Mills, Goodwin and Ankunding', 93);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (94, 94, 'Kuvalis, Williamson and Pfeffer', 94);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (95, 95, 'Daniel, Bosco and Macejkovic', 95);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (96, 96, 'Lubowitz Group', 96);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (97, 97, 'Mante, Howe and Schultz', 97);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (98, 98, 'Wiza-Rempel', 98);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (99, 99, 'Hermiston Inc', 99);
insert into kozmeticki_salon (mbf, pib, naziv, adresa_id) values (100, 100, 'Considine-Mills', 100);