insert into licenca (id, naziv) values (1, 'Makeup Application Licence');
insert into licenca (id, naziv) values (2, 'Spray Tan Licence');
insert into licenca (id, naziv) values (3, 'Perms Licence');
insert into licenca (id, naziv) values (4, 'Acne Treatment Licence');
insert into licenca (id, naziv) values (5, 'Acrylic Nails Licence');
insert into licenca (id, naziv) values (6, 'Beard Sculpting Licence');
insert into licenca (id, naziv) values (7, 'Blowouts Licence');
insert into licenca (id, naziv) values (8, 'Body Art Licence');
insert into licenca (id, naziv) values (9, 'Body Contouring Licence');
insert into licenca (id, naziv) values (10, 'Body Waxing Licence');
insert into licenca (id, naziv) values (11, 'Botox Licence');
insert into licenca (id, naziv) values (12, 'Braids Licence');
insert into licenca (id, naziv) values (13, 'Chemical Peel Licence');
insert into licenca (id, naziv) values (14, 'Hair Color Licence');
insert into licenca (id, naziv) values (15, 'Dermabrasion Licence');
insert into licenca (id, naziv) values (16, 'Eyebrow Tinting Licence');
insert into licenca (id, naziv) values (17, 'Eyelash Extensions Licence');
insert into licenca (id, naziv) values (18, 'Eyelash Tint Licence');
insert into licenca (id, naziv) values (19, 'Facelift Licence');
insert into licenca (id, naziv) values (20, 'Lash Lift Licence');
insert into licenca (id, naziv) values (21, 'Manicure Licence');
insert into licenca (id, naziv) values (22, 'Pedicure Licence');
insert into licenca (id, naziv) values (23, 'Makeup Application Licence');