insert into usluga (id, naziv) values (1, 'Makeup Application');
insert into usluga (id, naziv) values (2, 'Spray Tan');
insert into usluga (id, naziv) values (3, 'Perms');
insert into usluga (id, naziv) values (4, 'Acne Treatment');
insert into usluga (id, naziv) values (5, 'Acrylic Nails');
insert into usluga (id, naziv) values (6, 'Beard Sculpting');
insert into usluga (id, naziv) values (7, 'Blowouts');
insert into usluga (id, naziv) values (8, 'Body Art');
insert into usluga (id, naziv) values (9, 'Body Contouring');
insert into usluga (id, naziv) values (10, 'Body Waxing');
insert into usluga (id, naziv) values (11, 'Botox');
insert into usluga (id, naziv) values (12, 'Braids');
insert into usluga (id, naziv) values (13, 'Chemical Peel');
insert into usluga (id, naziv) values (14, 'Hair Color');
insert into usluga (id, naziv) values (15, 'Dermabrasion');
insert into usluga (id, naziv) values (16, 'Eyebrow Tinting');
insert into usluga (id, naziv) values (17, 'Eyelash Extensions');
insert into usluga (id, naziv) values (18, 'Eyelash Tint');
insert into usluga (id, naziv) values (19, 'Facelift');
insert into usluga (id, naziv) values (20, 'Lash Lift');
insert into usluga (id, naziv) values (21, 'Manicure');
insert into usluga (id, naziv) values (22, 'Pedicure');
insert into usluga (id, naziv) values (23, 'Makeup Application');